import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

public class addTaskFrame extends JFrame {
    public Task task;
    String storeWhere;
    // Variables declaration - do not modify
    private JComboBox<String> JComboBoxMonth;
    private JButton jButtonAddTask;
    private JComboBox<Integer> jComboBoxDay;
    private JComboBox<Integer> jComboBoxDays;
    private JComboBox<Integer> jComboBoxHours;
    private JComboBox<Integer> jComboBoxMinutes;
    private JComboBox<String> jComboBoxTaskCourse;
    private JComboBox<String> jComboBoxTaskType;
    private JComboBox<Integer> jComboBoxYear;
    private JLabel jLabelEnterName;
    private JLabel jLabelDay;
    private JLabel jLabelDays;
    private JLabel jLabelDueDate;
    private JLabel jLabelEstimateTime;
    private JLabel jLabelHours;
    private JLabel jLabelMinutes;
    private JLabel jLabelMonth;
    private JLabel jLabelTaskCourse;
    private JLabel jLabelTaskType;
    private JLabel jLabelYear;
    private JPanel jPanelTaskName;
    private JPanel jPanelDueDate;
    private JPanel jPanelEstimateTime;
    private JPanel jPanelTaskComments;
    private JPanel jPanelTaskSubmit;
    private JPanel jPanelTypeCourse;
    private JScrollPane jScrollPaneCommentsBox;
    private JTextArea jTextFieldComments;
    private JTextPane jTextPaneTaskName;
    // End of variables declaration
    /**
     * Creates new form taskAdd
     */
    public addTaskFrame(String storeWhere) {
        this.storeWhere = storeWhere;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Task");


        /**
         * Enter Task name panel and components
         */
        jPanelTaskName = new JPanel(new GridLayout(1,1));
        jLabelEnterName = new JLabel("Enter task name: ");
        jTextPaneTaskName = new JTextPane();

        jPanelTaskName.setLayout(new GridLayout(1,2, 0,0));
        jPanelTaskName.add(jLabelEnterName);
        jPanelTaskName.add(jTextPaneTaskName);
        jPanelTaskName.setBorder(BorderFactory.createEmptyBorder(0, 20, 0, 20));


        /**
         * Task type and task course panel and components
         */
        jPanelTypeCourse = new JPanel();
        jComboBoxTaskType = new JComboBox<>();
        jLabelTaskType = new JLabel();
        jLabelTaskCourse = new JLabel();
        jComboBoxTaskCourse = new JComboBox<>();
        jComboBoxTaskType.setModel(new DefaultComboBoxModel<>(new String[] { "Select One","Assignment", "Reading", "Lecture", "Exam Prep", "Other" }));
        jLabelTaskType.setText("Select Task Type:");
        jLabelTaskCourse.setText("Select Task Course:");
        jComboBoxTaskCourse.setModel(new DefaultComboBoxModel<>(new String[] { "Select One","Item 1", "Item 2", "Item 3", "Item 4" }));
        GroupLayout jPanelTypeCourseLayout = new GroupLayout(jPanelTypeCourse);
        jPanelTypeCourseLayout.setAutoCreateGaps(true);
        jPanelTypeCourseLayout.setAutoCreateContainerGaps(true);
        jPanelTypeCourse.setLayout(jPanelTypeCourseLayout);
        jPanelTypeCourseLayout.setHorizontalGroup(
                jPanelTypeCourseLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                        .addGroup(jPanelTypeCourseLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabelTaskType)
                                .addComponent(jComboBoxTaskType, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabelTaskCourse)
                                .addComponent(jComboBoxTaskCourse, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );
        jPanelTypeCourseLayout.setVerticalGroup(
                jPanelTypeCourseLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanelTypeCourseLayout.createSequentialGroup()
                                .addGap(0, 8, Short.MAX_VALUE)
                                .addGroup(jPanelTypeCourseLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxTaskType)
                                        .addComponent(jLabelTaskType)
                                        .addComponent(jLabelTaskCourse)
                                        .addComponent(jComboBoxTaskCourse, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        );


        /**
         * Task due date panel and components
         */
        jPanelDueDate = new JPanel();
        jLabelDueDate = new JLabel();
        JComboBoxMonth = new JComboBox<>();
        jComboBoxDay = new JComboBox<Integer>();
        jComboBoxYear = new JComboBox<Integer>();
        jLabelMonth = new JLabel();
        jLabelDay = new JLabel();
        jLabelYear = new JLabel();
        jLabelMonth.setText("Month:");
        jLabelDay.setText("Day:");
        jLabelYear.setText("Year:");
        jLabelDueDate.setText("Enter Task Due Date:");
        JComboBoxMonth.setModel(new DefaultComboBoxModel<>(new String[] {"January", "February", "March", "April", "May", "June", "July", "August","September","October","November", "December" }));
        jComboBoxDay.setModel(new DefaultComboBoxModel<Integer>(new Integer[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,14, 15, 16 ,17, 18, 19, 20, 21, 22, 23, 24, 25,26, 27, 28, 29, 30, 31 }));
        jComboBoxYear.setModel(new DefaultComboBoxModel<Integer>(new Integer[] { 2021, 2022, 2023, 2024 }));
        GroupLayout jPanelDueDateLayout = new GroupLayout(jPanelDueDate);
        jPanelDueDate.setLayout(jPanelDueDateLayout);
        jPanelDueDateLayout.setAutoCreateGaps(true);
        jPanelDueDateLayout.setAutoCreateContainerGaps(true);
        jPanelDueDateLayout.setHorizontalGroup(
                jPanelDueDateLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                        .addGroup(jPanelDueDateLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabelDueDate)
                                .addGap(32, 32, 32)
                                .addComponent(jLabelMonth)
                                .addComponent(JComboBoxMonth, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelDay)
                                .addComponent(jComboBoxDay, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelYear)
                                .addComponent(jComboBoxYear, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)

        ));
        jPanelDueDateLayout.setVerticalGroup(
                jPanelDueDateLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelDueDateLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelDueDateLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelDueDate)
                                        .addComponent(JComboBoxMonth, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxDay, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxYear, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelMonth)
                                        .addComponent(jLabelDay)
                                        .addComponent(jLabelYear))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );


        /**
         * Time estimation panel and components
         */
        jPanelEstimateTime = new JPanel();
        jLabelEstimateTime = new JLabel();
        jLabelDays = new JLabel();
        jLabelHours = new JLabel();
        jLabelMinutes = new JLabel();
        jComboBoxHours = new JComboBox<Integer>();
        jComboBoxMinutes = new JComboBox<Integer>();
        jComboBoxDays = new JComboBox<Integer>();

        jLabelEstimateTime.setText("Estimated Time to Complete Task:");
        jLabelHours.setText("Hrs:");
        jComboBoxHours.setModel(new DefaultComboBoxModel<Integer>(new Integer[] { 0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,14, 15, 16 ,17, 18,
                                                                                      19, 20, 21, 22, 23}));
        jLabelMinutes.setText("Mins:");
        jComboBoxMinutes.setModel(new DefaultComboBoxModel<Integer>(new Integer[] { 0, 5, 10, 15,20,25,30, 35, 40, 45,50,55}));
        jLabelDays.setText("Days:");
        jComboBoxDays.setModel(new DefaultComboBoxModel<Integer>(new Integer[] { 0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,14, 15, 16 ,17, 18, 19, 20, 21, 22, 23, 24, 25,26, 27, 28, 29, 30, 31 }));

        GroupLayout jPanelEstimateTimeLayout = new GroupLayout(jPanelEstimateTime);
        jPanelEstimateTimeLayout.setAutoCreateGaps(true);
        jPanelEstimateTimeLayout.setAutoCreateContainerGaps(true);
        jPanelEstimateTime.setLayout(jPanelEstimateTimeLayout);
        jPanelEstimateTimeLayout.setHorizontalGroup(
                jPanelEstimateTimeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelEstimateTimeLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabelEstimateTime)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelDays)
                                .addComponent(jComboBoxDays, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelHours)
                                .addComponent(jComboBoxHours, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelMinutes)
                                .addComponent(jComboBoxMinutes, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)

        ));

        jPanelEstimateTimeLayout.setVerticalGroup(
                jPanelEstimateTimeLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelEstimateTimeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelEstimateTimeLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelEstimateTime)
                                        .addComponent(jLabelHours)
                                        .addComponent(jComboBoxHours, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelMinutes)
                                        .addComponent(jComboBoxMinutes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelDays)
                                        .addComponent(jComboBoxDays, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(7, Short.MAX_VALUE))
        );


        /**
         * Comment text box panel and components
         */
        jPanelTaskComments = new JPanel(new GridLayout(1,1));
        jScrollPaneCommentsBox = new JScrollPane();
        jTextFieldComments = new JTextArea();
        jTextFieldComments.setColumns(20);
        jTextFieldComments.setRows(5);
        jTextFieldComments.setText("Enter all other information here"); // NOI18N
        jScrollPaneCommentsBox.setViewportView(jTextFieldComments);
        jPanelTaskComments.add(jScrollPaneCommentsBox);
        jPanelTaskComments.setBorder(BorderFactory.createEmptyBorder(0, 20, 0, 20));
        /**
         * Removes text description from text box when user clicks to type
         */
        jTextFieldComments.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                jTextFieldComments.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                jTextFieldComments.setText("Enter all other information here");
            }
        });


        /**
         * Submit button panel and components
         */
        jPanelTaskSubmit = new JPanel();

        jButtonAddTask = new JButton("Add Task"){
            {
                setSize(10,50);
                setMaximumSize(getSize());
            }
        };

        jPanelTaskSubmit.add(jButtonAddTask);
        jPanelTaskSubmit.setBorder(BorderFactory.createEmptyBorder(0, 20, 0, 20));
        jButtonAddTask.addActionListener(new ActionListener() {
            @Override
            /**
             * When use presses submit button the task will be prioritized and added to taskDB
             */
            public void actionPerformed(ActionEvent e) {
                Integer[] dueDate = { JComboBoxMonth.getSelectedIndex(), (Integer) jComboBoxDay.getSelectedItem(),(Integer)  jComboBoxYear.getSelectedItem()};
                Integer[] time = {(Integer) jComboBoxDays.getSelectedItem(), (Integer) jComboBoxHours.getSelectedItem(), (Integer) jComboBoxMinutes.getSelectedItem()};
                task = new Task(jTextPaneTaskName.getText(), jComboBoxTaskType.getSelectedItem()+"", jComboBoxTaskCourse.getSelectedItem()+"", dueDate, time,  jTextFieldComments.getText() );
                new prioritizeTasks(task, storeWhere);
                dispose();


            }
        });


        /**
         * Vertical layout of panels in frame
         */
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelTypeCourse, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelDueDate, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelEstimateTime, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelTaskComments, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelTaskName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelTaskSubmit, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelTaskName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelTypeCourse, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelDueDate, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelEstimateTime, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelTaskComments, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelTaskSubmit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
        );
        pack();

    }// </editor-fold>


}
